// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"VisuMZ_5_TiledMZ","status":true,"description":"[RPG Maker MZ] [Tier 5] [Version 0.16] [TiledMZ]","parameters":{"BreakHead":"----------------------------------","TiledMZ":"Plugin Parameters","ATTENTION":"READ THE HELP FILE","BreakSettings":"----------------------------------","BushDepth":"12","PriorityTileLimit":"256","ShadowVisibilitySwitch":"1","BreakEnd1":"----------------------------------","End Of":"Plugin Parameters","BreakEnd2":"----------------------------------"}}
];
